name: billmate
description: "Aplicativo de gerenciamento de finan√ßas pessoais e em grupo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.1
  dio: ^5.4.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_messaging: ^14.9.4
  uuid: ^4.4.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.2.2
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
